### ISSUE TITLE
i3 assign app to workspace 

### ISSUE THREAD

**Issue by cyrinux** [maximbaz/dotfiles#4] opened 2018-02-05 21:27 UTC
Hi Maxim,
Do you allready try and succeed to assign a app to a specific workspace when using i3-autoname-workspace.py?
I have weird behavior 
Regards

**Comment by maximbaz** [comment] 2018-02-05 21:39
Hey, `i3-autoname-workspace.py` is only about renaming workspaces, to assign app icons to the workspaces like that:

![image](https://user-images.githubusercontent.com/1177900/35830090-520f1a48-0ac5-11e8-9f40-47fa00c2e92a.png)

As for assigning apps to specific workspaces, this is supported by pure i3, it is done here:

https://github.com/maximbaz/dotfiles/blob/57e538c52056327ac3e02804d5baf3e38ec05a13/.i3/config#L18-L24

**Comment by cyrinux** [comment] 2018-02-05 22:01
Hmm, I will retry, thanks Maxim for your quick and complete reply yet. 
I have missing something during previous test I thinks. Shame on me, I use to use i3.

**Comment by cyrinux** [comment] 2018-02-06 07:33
Maxim, I think I have find what was my initial problem.
I have retry your rules, and it's work like a charm, but:
- I lose icon for floating app, like teamviewer for example. Is it an expected behavior?

![2018-02-06-083300_402x154_scrot](https://user-images.githubusercontent.com/519083/35846816-62276342-0b18-11e8-9c11-c21c15ebe7b7.png)

**Comment by maximbaz** [comment] 2018-02-06 09:16
I experience this too, but I never cared enough to investigate the cause 🙂 It was working for some time, and then with one of the i3wm upgrades it stopped working. If you want to investigate yourself, here's some info:

Querying for all windows is happening here:

https://github.com/maximbaz/dotfiles/blob/57e538c52056327ac3e02804d5baf3e38ec05a13/bin/i3-autoname-workspaces.py#L51-L54

So the problem is either in i3 itself, or in [i3ipc-python](https://github.com/acrisci/i3ipc-python) - the library that is used for communicating with i3 API. 

If you find a solution, let me know 🙂

**Comment by cyrinux** [comment] 2018-02-06 10:36
Thanks for info, i will search

**Comment by cyrinux** [comment] 2018-02-06 20:53
For the moment I can say it works with i3ipc tag v1.3.0 and i3 4.14.1

**Comment by acrisci** [comment] 2018-02-11 01:55
Try with the latest version I just released, 1.4.0, and let me know if it fixes it.

**Comment by cyrinux** [comment] 2018-02-11 10:05
Sorry @acrisci the issue seems to be still here, what can I do for help you?

**Comment by maximbaz** [comment] 2018-02-14 15:11
Fixed in the upstream 🎉

**Closed by maximbaz** 2018-02-14 15:11 UTC

**Comment by cyrinux** [comment] 2018-02-14 19:25
Cool! 😎

Le mer. 14 févr. 2018 à 16:11, Maxim Baz <notifications@github.com> a
écrit :
