### ISSUE TITLE
After a fresh installation UEFI entry is not bootable

### ISSUE THREAD

**Issue by n1ete** [maximbaz/dotfiles#24] opened 2020-09-30 12:37 UTC
For some reason I can’t Boot a fresh provisioned arch install ( using your dot repo ) anymore. Last fresh install was a while ago maybe the latest uefi changes in your dot repo are related to this?
I notice some errors when the „arch-secure-boot initial-setup“ command was called. 
Anyways, install doesn’t stop at the arch-secure-boot errors and runs trough. After reboot I reactivate secure-boot in bios and I can see that the „arch-secure-boot“ efi entry was created 
but it throws me immediately back to boot menu and didn’t boot any image...
Don’t know if something is broken with my changes to your repo or I encountered a bug.

I added a screenshot (sorry) since I am not aware of how to export a log from install on arch-live-System.
![9AC45C72-7444-475E-8941-8F3637AEA54B](https://user-images.githubusercontent.com/27276606/94685847-49681600-032a-11eb-8d2c-cc60e789815d.jpeg)

Any advise how to debug would be awesome 
Thanks in advance for your time and help :)

**Comment by maximbaz** [comment] 2020-10-02 19:45
hey @n1ete, I believe the issue should be fixed, please let me know if it isn't.

Check the recent commits, there is some cool stuff about detached LUKS header, but what's relevant for your issue is this:

https://github.com/maximbaz/dotfiles/blob/9fc46c3d3adb4efe29f0d21f4e2165478274a31b/install.sh#L116

This adds GPT partition labels, which are later used for kernel cmdline to boot:

https://github.com/maximbaz/dotfiles/blob/9fc46c3d3adb4efe29f0d21f4e2165478274a31b/install.sh#L194

I now use `/efi` instead of `/boot/efi`:

https://github.com/maximbaz/dotfiles/blob/9fc46c3d3adb4efe29f0d21f4e2165478274a31b/install.sh#L149

which is also the default in `arch-secure-boot`:

https://github.com/maximbaz/arch-secure-boot/blob/8ff824c9316de230f7b32742cbe7321ecf3c4569/arch-secure-boot#L11

and the correct ESP partition for boot is being located by checking where `/efi` is mounted:

https://github.com/maximbaz/arch-secure-boot/blob/8ff824c9316de230f7b32742cbe7321ecf3c4569/arch-secure-boot#L101

all in all this should hopefully generate the correct entries.

**Comment by n1ete** [comment] 2020-10-03 03:11
thanks for the update!

i added this to correct the hooks if luks header not detached, maybee you have some more creative ideas to take car of that, but for now this works well for me. ;)

```
if [ "$luks_header_device" == "part_root" ]; then
    arch-chroot /mnt sed -i "s/encrypt-dh/encrypt/g" /etc/mkinitcpio
fi
```

The efi entry that is created by arch-secure-boot picked still the wrong partition (1) so i created one with efibootmgr that points to partition 2.
after that everything is booting fine. 
i will take a further look later.

**Comment by maximbaz** [comment] 2020-10-03 08:58
`encrypt-dh` hook should work well even with non-detached header (I do hope that one day it gets merged into official `encrypt` hook), and in fact the syntax of the current `/etc/kernel/cmdline` relies on feature only available in `encrypt-dh` hook, even when the header is not detached - just be careful with that 👍 

I assume `arch-secure-boot` picked up a wrong entry if the chain of logic is somewhere broken, it looks at `$ESP` variable and checks what partition is mounted there, maybe it is set to incorrect value?

I'll close the ticket for now, but if you figure out what's wrong, please just share your finding here 😉

**Closed by maximbaz** 2020-10-03 08:58 UTC

**Comment by maximbaz** [comment] 2020-10-10 17:39
> I noticed that the efi boot entry is pointing to the first partition (the luks device) on the install drive. Shouldn't it point to the second partition ( /efi) ?

@n1ete I think I finally understand what went wrong in your case, it was probably caused by this issue: https://github.com/maximbaz/arch-secure-boot/pull/3

I'll release a fixed version of `arch-secure-boot` in a moment 😉  👍

**Comment by n1ete** [comment] 2020-10-11 21:05
@maximbaz Thanks,Great News! So far that brings my issues down to 1 actually (will open a separate issue for it)!
Another offtopic question: mounting/encrypting the luks drive at happens now 10x times faster.....has the encryption method changed aswell?

**Comment by maximbaz** [comment] 2020-10-11 21:18
First of all, when we switched from GRUB to UEFI boot, we are now decrypting the drive once and not two times during boot (in the past GRUB would decrypt it first time to access `/boot`, and then after you select Arch Linux entry in GRUB it would decrypt it again) - for me this is the biggest speed improvement.

GRUB only supports LUKS v1, so once we ditched GRUB, I converted to LUKS v2 format, I guess performance improvements could be here as well.

Finally, as the entire internet suggested, I went with using `argon2id` hashing algorithm instead of the default one, theoretically this could have produced some improvement as well.

Glad to hear that you are experiencing faster performance, regardless of the cause 😉 

Relevant line in the install.sh: https://github.com/maximbaz/dotfiles/blob/aead43f26f907fcfd8a8096ee8610b7a740554cc/install.sh#L130
